version: '3.1'

services:
  users_practice_pg:
    image: postgres:15.3
    container_name: users_practice_pg
    restart: always
    environment:
      POSTGRES_DB: users_p
      POSTGRES_USER: u_p
      POSTGRES_PASSWORD: secret12345
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
